site_name: System Docs
repo_name: system-docs

repo_url: https://github.com/Quarterhill-Inc/bos-system-docs
edit_uri: edit/main/docs/

theme:
  name: material
  logo: assets/qh-logo.svg
  favicon: assets/qh-favicon.svg
#   custom_dir: overrides
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - content.code.copy
    - search.suggest

plugins:
  - search
site_url: https://quarterhill-inc.github.io/bos-system-docs
markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

copyright: "© 2026 Quarterhill Inc. All rights reserved."
extra_css:
  - stylesheets/extra.css
extra_javascript:
  - https://unpkg.com/mermaid@10/dist/mermaid.min.js
  - javascripts/mermaid-init.js
nav:
  - Home: index.md
  - Overview:
      - System context: 00-overview/system-context.md
      - Glossary: 00-overview/glossary.md
  - Architecture:
      - High-level design: 01-architecture/high-level-design.md
      - UI ↔ Resource server: 01-architecture/ui-to-resource-server.md
      - Domain model: 01-architecture/domain-model.md
  - Security:
      - Threat model: 02-security/threat-model.md
      - AuthN/AuthZ: 02-security/authn-authz.md
      - Data protection: 02-security/data-protection.md
      - Secrets management: 02-security/secrets-management.md
      - Audit logging: 02-security/audit-logging.md
  - Deployment:
      - Environments: 03-deployment/environments.md
      - CI/CD: 03-deployment/ci-cd.md
      - Kubernetes: 03-deployment/kubernetes.md
      - Rollout strategy: 03-deployment/rollout-strategy.md
      - Observability: 03-deployment/observability.md
  - Networking:
      - Load balancer: 04-networking/load-balancer.md
      - Proxy / Ingress: 04-networking/proxy-ingress.md
      - TLS / SSL: 04-networking/tls-ssl.md
      - DNS: 04-networking/dns.md
      - WAF / DDoS: 04-networking/waf-ddos.md
  - Operations:
      - Runbooks: 05-operations/runbooks.md
      - Incident response: 05-operations/incident-response.md
      - Backups & DR: 05-operations/backups-dr.md
  - References:
      - Links: 06-references/links.md
      - ADRs: 06-references/adr/README.md
      - Templates: 06-references/adr/0001-template.md
  - Product:
      - Overview: 08-product/product.md
      - Glossary: 08-product/glossary.md
      - Adoption:
          - Incremental: 08-product/adoption/incremental-adoption.md
          - Migration: 08-product/adoption/migration-patterns.md
          - Strategy: 08-product/adoption/plug-unplug-strategy.md
      - Diagrams:
          - Adoption Phases: 08-product/diagrams/adoption-phases.md
          - Modular Overview: 08-product/diagrams/bos-modular-overview.md
          - Module Interactions: 08-product/diagrams/module-interactions.md
      - Integration:
          - Overview: 08-product/integration/integration-overview.md
          - Events & Contracts: 08-product/integration/events-and-contracts.md
          - External Systems: 08-product/integration/external-systems.md
      - Modules:
          - Account: 08-product/modules/accounts.md
          - Analytics: 08-product/modules/analytics.md
          - Case Management: 08-product/modules/case-management.md
          - Inventory: 08-product/modules/inventory.md
          - Notification: 08-product/modules/notifications.md
          - Payments: 08-product/modules/payments.md
          - Vehicle & Transponder: 08-product/modules/vehicles-transponders.md
      - Personas:
          - Admin: 08-product/personas/admin.md
          - Agent: 08-product/personas/agent.md
          - Online User: 08-product/personas/online-user.md
  - About:
      - Project: 07-project/project.md
      - Requirements: 07-project/requirement.md
      - Architecture decision records: 07-project/architecture-decision-records.md
      - Roadmap: 07-project/roadmap.md
      - Changelog: 07-project/changelog.md
      - Team: 07-project/team.md
      - Contact: 07-project/contact.md
      - Contributing: 07-project/contributing.md
      - Code of Conduct: 07-project/code-of-conduct.md
      - Security policy: 07-project/security-policy.md
      - Support: 07-project/support.md
      - FAQ: 07-project/faq.md
